[package]
name = "rauthp"
version = "0.1.0"
edition = "2021"

[dependencies]
base32ct = { version = "0.2.1", features = ["alloc"] }
clap = "4.5.20"
hmac = "0.12.1"
lazy_static = "1.5.0"
oo7 = "0.3.3"
regex = "1.11.0"
sha1 = "0.10.6"
tokio = { version = "1.40.0", features = ["full"] }
